services:
  bot:
    container_name: friendlyfire
    image: ghcr.io/cfazilleau/friendlyfire:main
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TOKEN=${TOKEN}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./config:/app/config
    networks:
      - friendlyfire

networks:
  friendlyfire:
    name: friendlyfire
